name: FRED External Adapter
description: An external adapter to get economic information
node_identifier: fred_cl_ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: FRED
    url: https://fred.stlouisfed.org/
parameters:
  - data_series